# Generated by Django 6.0.4 on 2026-05-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_lecon_exercice_lecon_image_lecon_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecon',
            name='niveau',
            field=models.CharField(default='7ème', max_length=20),
        ),
    ]
