# Generated by Django 6.0.4 on 2026-05-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_lecon_niveau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecon',
            name='exercice',
        ),
        migrations.RemoveField(
            model_name='lecon',
            name='image',
        ),
        migrations.RemoveField(
            model_name='lecon',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='lecon',
            name='pdf',
        ),
        migrations.AlterField(
            model_name='lecon',
            name='titre',
            field=models.CharField(max_length=200),
        ),
    ]
